# Permalinks
permalink:           pretty

# Setup
title:               Nora G. May
tagline:             Data Analyst, Data Scientist, and Data Enthusiast
url:                 http://noragmay.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nora G. May
  url:               www.linkedin.com/in/noragmay
  email:             noramay17@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/noragmay

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Resume: '/resume'
  Feed: '/index.html'
